### ISSUE TITLE
Draft a literature review on extant NLP techniques

### ISSUE THREAD

**Issue by marcdotson** [marcdotson/earnings-calls#5]
Start with the Josh Lee's papers ("Manager sentiment and stock returns," etc.) front end along with Jonah Berger's "Uniting the Tribes: Using Text for Marketing Insight" and then (in order of priority) Journal of Consumer Psychology, Journal of Customer Research, Journal of Marketing, Journal of Marketing Research, Marketing Science, and Quantitative Marketing and Economics.

Add bullets here of techniques that we should consider along with drafting the actual literature review for the paper.

**Comment by wtrumanrose** [comment]
[10.1177-0022242919873106-table4-0022242919873106.pdf](https://github.com/marcdotson/earnings-calls/files/9074190/10.1177-0022242919873106-table4-0022242919873106.pdf)

This table, from "Uniting the Tribes: Using Text for Marketing Insight" (Berger et al. 2020), has a reasonably thorough collection of techniques for text analysis in marketing and includes the relevant citations. There is a good degree of overlap between the usage of these different tools--alternative ways of grouping them could be considered.

**Comment by marcdotson** [comment]
Great, then how do you recommend we do it, @wtrumanrose? What makes sense given our application?
